2025-10-25 22:31:58,686 - ERROR - An error occurred!
Traceback (most recent call last):
  File "/var/folders/n9/hmvfpz0905z6n1yzq72hbw3c0000gn/T/ipykernel_42281/3078270388.py", line 28, in <module>
    client.connect(hostname = '192.168.64', username = 'testuser', password = 'TempPassword1')
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.13/site-packages/paramiko/client.py", line 384, in connect
    sock.connect(addr)
    ~~~~~~~~~~~~^^^^^^
TimeoutError: [Errno 60] Operation timed out
2025-10-25 22:32:45,791 - INFO - Connected (version 2.0, client OpenSSH_9.9p1)
2025-10-25 22:32:46,118 - INFO - Authentication (publickey) failed.
2025-10-25 22:32:46,236 - INFO - Authentication (password) successful!
2025-10-25 22:32:46,302 - INFO - [chan 0] Opened sftp connection (server version 3)
2025-10-25 22:33:46,563 - INFO - [chan 0] sftp session closed.
2025-10-25 22:40:11,209 - INFO - Connected (version 2.0, client OpenSSH_9.9p1)
2025-10-25 22:40:11,555 - INFO - Authentication (publickey) failed.
2025-10-25 22:40:11,614 - INFO - Authentication (password) successful!
2025-10-25 22:40:11,671 - INFO - [chan 0] Opened sftp connection (server version 3)
2025-10-25 22:40:33,751 - INFO - [chan 0] sftp session closed.
2025-10-25 22:42:20,604 - INFO - Connected (version 2.0, client OpenSSH_9.9p1)
2025-10-25 22:42:20,912 - INFO - Authentication (publickey) failed.
2025-10-25 22:42:20,970 - INFO - Authentication (password) successful!
2025-10-25 22:42:21,046 - INFO - [chan 0] Opened sftp connection (server version 3)
2025-10-25 22:43:21,462 - INFO - [chan 0] sftp session closed.
