{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "4759a533-04f8-4f74-85b6-9752c81ca7e3",
   "metadata": {},
   "outputs": [
    {
     "ename": "TypeError",
     "evalue": "TextIOWrapper.write() takes exactly one argument (2 given)",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mSMTPAuthenticationError\u001b[0m                   Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[1], line 43\u001b[0m\n\u001b[1;32m     42\u001b[0m smtp_object\u001b[38;5;241m.\u001b[39mehlo()\n\u001b[0;32m---> 43\u001b[0m smtp_object\u001b[38;5;241m.\u001b[39mlogin(email_address,email_pass)\n\u001b[1;32m     44\u001b[0m from_address \u001b[38;5;241m=\u001b[39m email_address\n",
      "File \u001b[0;32m/opt/anaconda3/lib/python3.13/smtplib.py:750\u001b[0m, in \u001b[0;36mSMTP.login\u001b[0;34m(self, user, password, initial_response_ok)\u001b[0m\n\u001b[1;32m    749\u001b[0m \u001b[38;5;66;03m# We could not login successfully.  Return result of last attempt.\u001b[39;00m\n\u001b[0;32m--> 750\u001b[0m \u001b[38;5;28;01mraise\u001b[39;00m last_exception\n",
      "File \u001b[0;32m/opt/anaconda3/lib/python3.13/smtplib.py:739\u001b[0m, in \u001b[0;36mSMTP.login\u001b[0;34m(self, user, password, initial_response_ok)\u001b[0m\n\u001b[1;32m    738\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m--> 739\u001b[0m     (code, resp) \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mauth(\n\u001b[1;32m    740\u001b[0m         authmethod, \u001b[38;5;28mgetattr\u001b[39m(\u001b[38;5;28mself\u001b[39m, method_name),\n\u001b[1;32m    741\u001b[0m         initial_response_ok\u001b[38;5;241m=\u001b[39minitial_response_ok)\n\u001b[1;32m    742\u001b[0m     \u001b[38;5;66;03m# 235 == 'Authentication successful'\u001b[39;00m\n\u001b[1;32m    743\u001b[0m     \u001b[38;5;66;03m# 503 == 'Error: already authenticated'\u001b[39;00m\n",
      "File \u001b[0;32m/opt/anaconda3/lib/python3.13/smtplib.py:662\u001b[0m, in \u001b[0;36mSMTP.auth\u001b[0;34m(self, mechanism, authobject, initial_response_ok)\u001b[0m\n\u001b[1;32m    661\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m (code, resp)\n\u001b[0;32m--> 662\u001b[0m \u001b[38;5;28;01mraise\u001b[39;00m SMTPAuthenticationError(code, resp)\n",
      "\u001b[0;31mSMTPAuthenticationError\u001b[0m: (535, b'5.7.8 Username and Password not accepted. For more information, go to\\n5.7.8  https://support.google.com/mail/?p=BadCredentials ffacd0b85a97d-429952d9e80sm10130062f8f.28 - gsmtp')",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[1], line 49\u001b[0m\n\u001b[1;32m     47\u001b[0m     messages \u001b[38;5;241m=\u001b[39m []\n\u001b[1;32m     48\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mException\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[0;32m---> 49\u001b[0m     f\u001b[38;5;241m.\u001b[39mwrite(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mFailed to send email:\u001b[39m\u001b[38;5;124m\"\u001b[39m, e)\n\u001b[1;32m     52\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m     53\u001b[0m     \u001b[38;5;66;03m#Paramiko instancw\u001b[39;00m\n\u001b[1;32m     54\u001b[0m     client \u001b[38;5;241m=\u001b[39m paramiko\u001b[38;5;241m.\u001b[39mSSHClient()\n",
      "\u001b[0;31mTypeError\u001b[0m: TextIOWrapper.write() takes exactly one argument (2 given)"
     ]
    }
   ],
   "source": [
    "#Inbound Process\n",
    "import logging\n",
    "import paramiko\n",
    "import sys\n",
    "import shutil\n",
    "import time\n",
    "import posixpath\n",
    "import datetime\n",
    "import os\n",
    "import smtplib, getpass, json\n",
    "\n",
    "#Working with config file\n",
    "with open(\"config.json\") as f:\n",
    "    config = json.load(f)\n",
    "\n",
    "#sftp credentials\n",
    "sftp_host = config[\"sftp\"][\"hostname\"]\n",
    "sftp_user = config[\"sftp\"][\"username\"]\n",
    "sftp_pass = config[\"sftp\"][\"password\"]\n",
    "\n",
    "#email credentials\n",
    "email_address = config[\"email\"][\"address\"]\n",
    "email_pass = config[\"email\"][\"password\"]\n",
    "\n",
    "#path variables\n",
    "local = os.path.join(os.getcwd(), 'Processing')\n",
    "remote = '/Files/ScannedDocs/'\n",
    "archive = os.path.join(local, \"Archive\")\n",
    "\n",
    "#Logging\n",
    "get_date = datetime.datetime.now().strftime(\"%Y%m%d_%H%M\")\n",
    "logging.basicConfig(level=logging.ERROR, filename=f\"/Users/homebase/Desktop/Python/Udemy Course/Milestone Projects/OPUS/Processing/Log/InboundError/{get_date}-errorlog.log\", filemode=\"w\", format=\"%(asctime)s - %(levelname)s - %(message)s\")\n",
    "\n",
    "with open(f\"/Users/homebase/Desktop/Python/Udemy Course/Milestone Projects/OPUS/Processing/Log/Inbound/{get_date}\", 'a') as f:\n",
    "    f.write(f\"============= {get_date} Processing =============\\n\")\n",
    "\n",
    "    try:\n",
    "        #Working with email\n",
    "        smtp_object = smtplib.SMTP(\"smtp.gmail.com\", 587)\n",
    "        smtp_object.ehlo()\n",
    "        smtp_object.starttls()\n",
    "        smtp_object.ehlo()\n",
    "        smtp_object.login(email_address,email_pass)\n",
    "        from_address = email_address\n",
    "        to_address = email_address\n",
    "        subject = \"Inbound Reporting\"\n",
    "        messages = []\n",
    "    except Exception as e:\n",
    "        f.write(\"Failed to send email:\", e)\n",
    "\n",
    "    \n",
    "    try:\n",
    "        #Paramiko instancw\n",
    "        client = paramiko.SSHClient()\n",
    "        client.load_system_host_keys()\n",
    "        client.set_missing_host_key_policy(paramiko.AutoAddPolicy())\n",
    "        client.connect(hostname = '192.168.64.3', username = 'testuser', password = 'TempPassword1')\n",
    "        f.write(\"Connection successful\\n\")  \n",
    "        messages.append(\"SFTP Connection Successful\")\n",
    "        try:\n",
    "            with client.open_sftp() as sftp:\n",
    "                for folder, sub_folders, files in os.walk(local):\n",
    "                    if os.path.basename(folder) in ['Archive', 'Log', 'Outbound']: #Ignore these folders\n",
    "                        continue\n",
    "            \n",
    "                    for file in files:\n",
    "                        if file.endswith(\".pdf\") or file.endswith(\".csv\"):\n",
    "                            local_source = os.path.join(folder, file)\n",
    "                            remote_destination = posixpath.join(remote, file)\n",
    "                            sftp.put(local_source, remote_destination)\n",
    "                            f.write(f\"Uploading {os.path.basename(local_source)} to {remote}\\n\")\n",
    "                            messages.append(f\"Uploading {os.path.basename(local_source)} to {remote}\")\n",
    "                        if file.endswith(\".pdf\"):\n",
    "                            time.sleep(2)\n",
    "            \n",
    "                        if file.endswith(\".csv\"):\n",
    "                            time.sleep(10)\n",
    "        except Exception as e:\n",
    "            logging.exception(\"An error occurred!: {e}\")\n",
    "            messages.append(f\"Error handling {file}\")\n",
    "            sys.exit() #to stop the script if an error occurs\n",
    "            \n",
    "    except Exception as e:\n",
    "        logging.exception(f\"Error during SFTP connection: {e}\")\n",
    "        messages.append(f\"Error during SFTP connection: {e}\")\n",
    "        sys.exit() #to stop the script if an error occurs\n",
    "    finally:\n",
    "        client.close()\n",
    "    try: \n",
    "        for folder in os.listdir(local):\n",
    "            if os.path.basename(folder) in ['Archive', 'Log', '.ipynb_checkpoints', 'Outbound']: #Ignore these folders\n",
    "                    continue\n",
    "            source = os.path.join(local, folder)\n",
    "            shutil.move(source, archive)\n",
    "            f.write(f\"{os.path.basename(folder)} moved into Archive\")\n",
    "            messages.append(f\"{os.path.basename(folder)} moved into Archive\")\n",
    "    except Exception as e:\n",
    "            logging.exception(f\"Error handling {folder}: {e}\")\n",
    "            messages.append(f\"Error handling {folder}\")\n",
    "    finally:\n",
    "        msg_body = \"\\n\".join(messages)\n",
    "        msg = \"Subject: \"+subject+'\\n'+ msg_body\n",
    "        smtp_object.sendmail(from_address,to_address,msg)\n",
    "        smtp_object.quit()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "bb44f0ce-35ff-47c7-8c45-0c19bef9505d",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
